import type { Bilingual } from "@/content/services";

export type StackGroup = {
  label: Bilingual;
  icon: string; // lucide key, resolved in TechStack.tsx
  items: string[];
};

export const stackGroups: StackGroup[] = [
  {
    label: { en: "Languages", hi: "भाषाएँ" },
    icon: "code",
    items: [
      "JavaScript",
      "TypeScript",
      "PHP",
      "Python",
      "Go",
      "Ruby",
      "Java",
      "Kotlin",
      "Swift",
      "Dart",
      "SQL",
      "HTML5",
      "CSS3",
    ],
  },
  {
    label: { en: "Frontend", hi: "फ्रंटएंड" },
    icon: "layout",
    items: [
      "React",
      "Next.js",
      "Vue.js",
      "Nuxt",
      "Angular",
      "Svelte / SvelteKit",
      "Astro",
      "Remix",
      "SolidJS",
      "Alpine.js",
      "jQuery",
      "Redux / Zustand",
      "TanStack Query",
      "Tailwind CSS",
      "Bootstrap",
      "Sass",
      "GSAP",
      "Framer Motion",
    ],
  },
  {
    label: { en: "Backend & APIs", hi: "बैकएंड और API" },
    icon: "server",
    items: [
      "Node.js",
      "Express",
      "NestJS",
      "Fastify",
      "Laravel",
      "Symfony",
      "Django",
      "Flask",
      "FastAPI",
      "Ruby on Rails",
      "Spring Boot",
      ".NET",
      "GraphQL",
      "tRPC",
      "REST",
      "WebSockets",
    ],
  },
  {
    label: { en: "CMS & eCommerce", hi: "CMS और ईकॉमर्स" },
    icon: "shopping-bag",
    items: [
      "WordPress",
      "Magento 2",
      "Shopify",
      "WooCommerce",
      "Strapi",
      "Sanity",
      "Contentful",
      "Payload CMS",
      "Directus",
      "Ghost",
      "Prismic",
      "Drupal",
    ],
  },
  {
    label: { en: "Mobile", hi: "मोबाइल" },
    icon: "smartphone",
    items: ["React Native", "Expo", "Flutter", "Kotlin (Android)", "Swift (iOS)", "Ionic", "Capacitor"],
  },
  {
    label: { en: "Databases & ORM", hi: "डेटाबेस और ORM" },
    icon: "database",
    items: [
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "SQLite",
      "Redis",
      "Supabase",
      "Firebase",
      "PlanetScale",
      "Prisma",
      "Drizzle",
      "TypeORM",
    ],
  },
  {
    label: { en: "Cloud & DevOps", hi: "क्लाउड और DevOps" },
    icon: "cloud",
    items: [
      "Vercel",
      "AWS",
      "Google Cloud",
      "Cloudflare",
      "Netlify",
      "DigitalOcean",
      "Railway",
      "Docker",
      "Kubernetes",
      "GitHub Actions",
      "Nginx",
      "Linux",
    ],
  },
  {
    label: { en: "Payments & integrations", hi: "पेमेंट और इंटीग्रेशन" },
    icon: "credit-card",
    items: [
      "Razorpay",
      "Stripe",
      "PayPal",
      "PhonePe",
      "Twilio",
      "Resend",
      "SendGrid",
      "WhatsApp Cloud API",
      "OAuth / Auth.js",
      "Firebase Auth",
    ],
  },
  {
    label: { en: "Analytics & marketing", hi: "एनालिटिक्स और मार्केटिंग" },
    icon: "line-chart",
    items: [
      "GA4",
      "Google Ads",
      "Google Tag Manager",
      "Search Console",
      "Meta Pixel",
      "Looker Studio",
      "Hotjar",
      "Mixpanel",
      "Ahrefs",
      "Semrush",
    ],
  },
];
